{% set name = 'ada-py' %}
{% set version = '0.2.12' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Krande/adapy/archive/v{{ version }}.tar.gz
  sha256: 480dff4a6b9a128ff58e828175e8343766f0e11863e0bbf7f38ac027849d452f

build:
  noarch: python
  script: python -m pip install . --no-deps -vv
  number: 0
  entry_points:
    - ada-viewer=ada.visit.websocket_cli:ws_cli_app

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - python >=3.10
    - kaleido-core 0.1.0
    - numpy
    - hdf5
    - h5py
    - ifcopenshell
    - pythonocc-core
    - python-gmsh
    - pyquaternion
    - trimesh
    - occt >=7.7.2
    - send2trash
    - meshio
    - websockets
    - plotly
    - python-kaleido
    - calculix
    - ipywidgets
    - jupyterlab
    - pyparsing
    - pyglfw
    - pygfx

test:
  source_files:
    - tests
    - files
    - examples
  requires:
    - pytest
    - pytest-cov
  imports:
    - ada
  commands:
    - pytest tests --ignore=tests/fem --cov=ada --cov-report=xml

about:
  home: https://github.com/krande/adapy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
