{% set name = "ada-py" %}
{% set version = "0.3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Krande/adapy/archive/v{{ version }}.tar.gz
  sha256: bc1b5548088a657b07dbf65d97bc9ac61ddd5a83da1b6811db7f444bebac4ebe

build:
  noarch: python
  script: python -m pip install . --no-deps -vv
  number: 0
  entry_points:
    - ada-viewer=ada.visit.websocket_cli:ws_cli_app

requirements:
  host:
    - pip
    - setuptools
    - python >=3.10
  run:
    - python >=3.10
    - kaleido-core 0.1.0
    - numpy
    - hdf5
    - h5py
    - ifcopenshell
    - bcf-client
    - pythonocc-core
    - python-gmsh
    - pyquaternion
    - trimesh
    - occt >=7.7.2
    - send2trash
    - meshio
    - websockets
    - plotly
    - python-kaleido
    - calculix
    - ipywidgets
    - jupyterlab
    - pyparsing
    - pyglfw
    - pygfx
    - python-flatbuffers

test:
  source_files:
    - tests
    - files
  requires:
    - pytest
    - pytest-cov
    - pytest-asyncio
  imports:
    - ada
  commands:
    - pytest tests --ignore=tests/fem --ignore=tests/profiling --ignore=tests/examples --ignore=tests/full/frontend --cov=ada --cov-report=xml

about:
  home: https://github.com/krande/adapy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
